#!/bin/bash
cd $(dirname $(dirname $0)) || exit

mkdir -p logs

./scripts/initialize
docker-compose down
docker-compose build
docker-compose up -d
docker-compose exec -T site python3 manage.py migrate
./scripts/copy_static
